### Get current session
GET http://127.0.0.1:8000/api/auth/browser/v1/auth/session

### Signup
POST http://127.0.0.1:8000/api/auth/browser/v1/auth/signup
Content-Type: application/json
Cookie: csrftoken=CSRF_TOKEN
X-CSRFToken: CSRF_TOKEN

{
  "email": "user@example.com",
  "password": "PASSWORD"
}

### Login
POST http://127.0.0.1:8000/api/auth/browser/v1/auth/login
Content-Type: application/json
Cookie: csrftoken=CSRF_TOKEN
X-CSRFToken: CSRF_TOKEN

{
  "email": "user@example.com",
  "password": "PASSWORD"
}

### Check authenticated session
GET http://127.0.0.1:8000/api/auth/browser/v1/auth/session
Cookie: csrftoken=CSRF_TOKEN; sessionid=SESSION_ID

###

### Logout
DELETE http://127.0.0.1:8000/api/auth/browser/v1/auth/session
Cookie: csrftoken=CSRF_TOKEN; sessionid=SESSION_ID
X-CSRFToken: CSRF_TOKEN