[project]
name = "openbooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "django-allauth[headless,socialaccount]>=65.19.1",
    "djangorestframework>=3.18.0",
    "fido2>=2.2.1",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"